import type { ImageSourcePropType } from 'react-native';

/** Bundled catalog fly photos keyed by normalized pattern name. */
const FLY_IMAGES_BY_NAME: Record<string, ImageSourcePropType> = {
  '20 incher': require('@/assets/images/flies/20-incher.png'),
  adams: require('@/assets/images/flies/adams.png'),
  'adams wulff': require('@/assets/images/flies/adams-wulff.png'),
  alexandra: require('@/assets/images/flies/alexandra.png'),
  'amano kebari': require('@/assets/images/flies/amano-kebari.png'),
  ant: require('@/assets/images/flies/ant.png'),
  'barr\'s emerger': require('@/assets/images/flies/barrs-emerger.png'),
  beetle: require('@/assets/images/flies/beetle.png'),
  'bh hare\'s ear nymph': require('@/assets/images/flies/bh-hares-ear-nymph.png'),
  'bh pheasant tail': require('@/assets/images/flies/bh-pheasant-tail.jpg'),
  'bird\'s nest': require('@/assets/images/flies/birds-nest.png'),
  'black beauty': require('@/assets/images/flies/black-beauty.png'),
  blowtorch: require('@/assets/images/flies/blowtorch.png'),
  brassie: require('@/assets/images/flies/brassie.png'),
  'bloody butcher': require('@/assets/images/flies/bloody-butcher.png'),
  'blue quill': require('@/assets/images/flies/blue-quill.png'),
  'blue wing olive': require('@/assets/images/flies/blue-wing-olive.png'),
  'brown drake': require('@/assets/images/flies/brown-drake.png'),
  'chernobyl ant': require('@/assets/images/flies/chernobyl-ant.png'),
  'chubby chernobyl': require('@/assets/images/flies/chubby-chernobyl.png'),
  'cdc emerger': require('@/assets/images/flies/cdc-emerger.png'),
  comparadun: require('@/assets/images/flies/comparadun.png'),
  'copper john': require('@/assets/images/flies/copper-john.png'),
  'craven\'s juju baetis': require('@/assets/images/flies/cravens-juju-baetis.png'),
  'cripple bwo': require('@/assets/images/flies/cripple-bwo.png'),
  'dave\'s hopper': require('@/assets/images/flies/daves-hopper.png'),
  'elk hair caddis': require('@/assets/images/flies/elk-hair-caddis.png'),
  egg: require('@/assets/images/flies/egg.png'),
  'electric prince': require('@/assets/images/flies/electric-prince.png'),
  'flashback pheasant tail': require('@/assets/images/flies/flashback-pheasant-tail.png'),
  frenchie: require('@/assets/images/flies/frenchie.png'),
  'flying ant': require('@/assets/images/flies/flying-ant.png'),
  'girdle bug': require('@/assets/images/flies/girdle-bug.png'),
  'goddard caddis': require('@/assets/images/flies/goddard-caddis.png'),
  'gray drake': require('@/assets/images/flies/gray-drake.png'),
  'green drake': require('@/assets/images/flies/green-drake.png'),
  'gold ribbed hare\'s ear': require('@/assets/images/flies/gold-ribbed-hares-ear.png'),
  'golden stone nymph': require('@/assets/images/flies/golden-stone-nymph.png'),
  'griffiths gnat': require('@/assets/images/flies/griffiths-gnat.png'),
  'h&l variant': require('@/assets/images/flies/h-and-l-variant.png'),
  hendrickson: require('@/assets/images/flies/hendrickson.png'),
  'henryville special': require('@/assets/images/flies/henryville-special.png'),
  'hippie stomper': require('@/assets/images/flies/hippie-stomper.png'),
  'hares ear nymph': require('@/assets/images/flies/hares-ear-nymph.png'),
  'higa\'s sos': require('@/assets/images/flies/higas-sos.png'),
  'idaho killer kebari': require('@/assets/images/flies/idaho-killer-kebari.png'),
  'ishigaki kebari': require('@/assets/images/flies/ishigaki-kebari.png'),
  humpy: require('@/assets/images/flies/humpy.png'),
  'iron lotus': require('@/assets/images/flies/iron-lotus.png'),
  'jigged frenchie': require('@/assets/images/flies/jigged-frenchie.png'),
  'jigged prince': require('@/assets/images/flies/jigged-prince.png'),
  'joe\'s hopper': require('@/assets/images/flies/joes-hopper.png'),
  'juju baetis': require('@/assets/images/flies/juju-baetis.png'),
  'kamikaze salmonfly': require('@/assets/images/flies/kamikaze-salmonfly.png'),
  klinkhammer: require('@/assets/images/flies/klinkhammer.png'),
  'leadwing coachman wet': require('@/assets/images/flies/leadwing-coachman-wet.png'),
  'light cahill': require('@/assets/images/flies/light-cahill.png'),
  'lightning bug': require('@/assets/images/flies/lightning-bug.png'),
  'march brown': require('@/assets/images/flies/march-brown.png'),
  'march brown wet': require('@/assets/images/flies/march-brown-wet.png'),
  'morrish hopper': require('@/assets/images/flies/morrish-hopper.png'),
  'mop fly': require('@/assets/images/flies/mop-fly.png'),
  'no hackle dry': require('@/assets/images/flies/no-hackle-dry.png'),
  'oki kebari': require('@/assets/images/flies/oki-kebari.png'),
  'orange stimulator': require('@/assets/images/flies/orange-stimulator.png'),
  'pale morning dun': require('@/assets/images/flies/pale-morning-dun.png'),
  'parachute adams': require('@/assets/images/flies/parachute-adams.png'),
  'parachute ant': require('@/assets/images/flies/parachute-ant.png'),
  'parachute hopper': require('@/assets/images/flies/parachute-hopper.png'),
  partridge: require('@/assets/images/flies/partridge.png'),
  'pat\'s rubber legs': require('@/assets/images/flies/pats-rubber-legs.png'),
  perdigon: require('@/assets/images/flies/perdigon.png'),
  'pheasant tail nymph': require('@/assets/images/flies/pheasant-tail-nymph.png'),
  'poison tung': require('@/assets/images/flies/poison-tung.png'),
  'prince nymph': require('@/assets/images/flies/prince-nymph.png'),
  'psycho prince': require('@/assets/images/flies/psycho-prince.png'),
  'quigley\'s film critic': require('@/assets/images/flies/quigleys-film-critic.png'),
  'rainbow warrior': require('@/assets/images/flies/rainbow-warrior.png'),
  'red quill': require('@/assets/images/flies/red-quill.png'),
  renegade: require('@/assets/images/flies/renegade.png'),
  'reverse hackle kebari': require('@/assets/images/flies/reverse-hackle-kebari.jpg'),
  'royal coachman': require('@/assets/images/flies/royal-coachman.png'),
  'royal trude': require('@/assets/images/flies/royal-trude.png'),
  'royal wulff': require('@/assets/images/flies/royal-wulff.png'),
  rs2: require('@/assets/images/flies/rs2.png'),
  'sakasa kebari': require('@/assets/images/flies/sakasa-kebari.png'),
  'san juan worm': require('@/assets/images/flies/san-juan-worm.png'),
  'sexy walt\'s hare\'s ear': require('@/assets/images/flies/sexy-walts-hares-ear.png'),
  'sexy walt\'s worm': require('@/assets/images/flies/sexy-walts-worm.png'),
  'shimmer bugger': require('@/assets/images/flies/shimmer-bugger.png'),
  'soft hackle': require('@/assets/images/flies/soft-hackle.png'),
  'spanish bullet': require('@/assets/images/flies/spanish-bullet.png'),
  'sparkle dun': require('@/assets/images/flies/sparkle-dun.png'),
  'sparkle pupa': require('@/assets/images/flies/sparkle-pupa.png'),
  'squirmy worm': require('@/assets/images/flies/squirmy-worm.png'),
  stimulator: require('@/assets/images/flies/stimulator.png'),
  'takayama sakasa kebari': require('@/assets/images/flies/takayama-sakasa-kebari.png'),
  'top secret midge': require('@/assets/images/flies/top-secret-midge.png'),
  trico: require('@/assets/images/flies/trico.png'),
  trude: require('@/assets/images/flies/trude.png'),
  'tungsten jig (drop pt)': require('@/assets/images/flies/tungsten-jig-drop-pt.png'),
  'wd-40': require('@/assets/images/flies/wd-40.png'),
  'white wulff': require('@/assets/images/flies/white-wulff.png'),
  'woolly bugger': require('@/assets/images/flies/woolly-bugger.png'),
  'x-caddis': require('@/assets/images/flies/x-caddis.png'),
  'yellow sally': require('@/assets/images/flies/yellow-sally.png'),
  'zebra midge': require('@/assets/images/flies/zebra-midge.png'),
  'zug bug': require('@/assets/images/flies/zug-bug.png'),
};

function normalizeFlyName(name: string): string {
  return name.trim().toLowerCase();
}

export function getBundledFlyImageSource(name: string | null | undefined): ImageSourcePropType | null {
  if (!name?.trim()) return null;
  return FLY_IMAGES_BY_NAME[normalizeFlyName(name)] ?? null;
}

export const BUNDLED_FLY_IMAGE_NAMES = Object.keys(FLY_IMAGES_BY_NAME).map(
  (k) => k.replace(/\b\w/g, (c) => c.toUpperCase()),
);
