-- Seed extended fly_catalog (top ~150 patterns). photo_url left null for later.
-- Skips rows that already exist (same name + type as migration 013 or prior runs).

insert into fly_catalog (name, type, presentation) values
  ('Adams', 'fly', 'dry'),
  ('Amano Kebari', 'fly', 'wet'),
  ('Alexandra', 'fly', 'wet'),
  ('Ant', 'fly', 'dry'),
  ('Adams Wulff', 'fly', 'dry'),
  ('Barr''s Emerger', 'fly', 'emerger'),
  ('Batwing Emerger', 'fly', 'emerger'),
  ('Beetle', 'fly', 'dry'),
  ('BH Hare''s Ear Nymph', 'fly', 'nymph'),
  ('BH Pheasant Tail', 'fly', 'nymph'),
  ('BH Prince Nymph', 'fly', 'nymph'),
  ('Bird''s Nest', 'fly', 'nymph'),
  ('Black Beauty', 'fly', 'nymph'),
  ('Black Nose Dace', 'fly', 'streamer'),
  ('Bloody Butcher', 'fly', 'wet'),
  ('Blowtorch', 'fly', 'nymph'),
  ('Blue Quill', 'fly', 'dry'),
  ('Blue Wing Olive', 'fly', 'dry'),
  ('Bow River Bugger', 'fly', 'streamer'),
  ('Brassie', 'fly', 'nymph'),
  ('Brown Drake', 'fly', 'dry'),
  ('Buckskin Caddis', 'fly', 'dry'),
  ('CDC Caddis', 'fly', 'dry'),
  ('CDC Emerger', 'fly', 'emerger'),
  ('CDC Midge', 'fly', 'dry'),
  ('Chernobyl Ant', 'fly', 'dry'),
  ('Chubby Chernobyl', 'fly', 'dry'),
  ('Circus Peanut', 'fly', 'streamer'),
  ('Cluster Midge', 'fly', 'dry'),
  ('Comparadun', 'fly', 'dry'),
  ('Conehead Woolly Bugger', 'fly', 'streamer'),
  ('Copper John', 'fly', 'nymph'),
  ('Copper Tiger', 'fly', 'nymph'),
  ('Craven''s Juju Baetis', 'fly', 'nymph'),
  ('Cripple BWO', 'fly', 'dry'),
  ('Dave''s Hopper', 'fly', 'dry'),
  ('Double Bunny', 'fly', 'streamer'),
  ('Egg', 'fly', 'nymph'),
  ('Egg Sucking Leech', 'fly', 'streamer'),
  ('Electric Prince', 'fly', 'nymph'),
  ('Elk Hair Caddis', 'fly', 'dry'),
  ('Fiery Brown', 'fly', 'wet'),
  ('Flashback Pheasant Tail', 'fly', 'nymph'),
  ('Flying Ant', 'fly', 'dry'),
  ('Frenchie', 'fly', 'nymph'),
  ('Girdle Bug', 'fly', 'nymph'),
  ('Goddard Caddis', 'fly', 'dry'),
  ('Golden Stone Nymph', 'fly', 'nymph'),
  ('Gold Ribbed Hare''s Ear', 'fly', 'nymph'),
  ('Gray Drake', 'fly', 'dry'),
  ('Green Drake', 'fly', 'dry'),
  ('Griffiths Gnat', 'fly', 'dry'),
  ('Hares Ear Nymph', 'fly', 'nymph'),
  ('H&L Variant', 'fly', 'dry'),
  ('Hendrickson', 'fly', 'dry'),
  ('Henryville Special', 'fly', 'dry'),
  ('Higa''s SOS', 'fly', 'nymph'),
  ('Hippie Stomper', 'fly', 'dry'),
  ('Hot Spot Frenchie', 'fly', 'nymph'),
  ('Humpy', 'fly', 'dry'),
  ('Idaho Killer Kebari', 'fly', 'wet'),
  ('Invicta', 'fly', 'wet'),
  ('Iron Lotus', 'fly', 'nymph'),
  ('Ishigaki Kebari', 'fly', 'wet'),
  ('Jigged Frenchie', 'fly', 'nymph'),
  ('Jigged Prince', 'fly', 'nymph'),
  ('Joe''s Hopper', 'fly', 'dry'),
  ('Juju Baetis', 'fly', 'nymph'),
  ('Killer Kebari', 'fly', 'wet'),
  ('Klinkhammer', 'fly', 'emerger'),
  ('Kuwabara Kebari', 'fly', 'wet'),
  ('Leadwing Coachman Wet', 'fly', 'wet'),
  ('Leech', 'fly', 'streamer'),
  ('Light Cahill', 'fly', 'dry'),
  ('Lightning Bug', 'fly', 'nymph'),
  ('Little Black Stone', 'fly', 'nymph'),
  ('March Brown', 'fly', 'dry'),
  ('March Brown Wet', 'fly', 'wet'),
  ('Mickey Finn', 'fly', 'streamer'),
  ('Midges (generic)', 'fly', 'emerger'),
  ('Montana Nymph', 'fly', 'nymph'),
  ('Mop Fly', 'fly', 'nymph'),
  ('Morrish Hopper', 'fly', 'dry'),
  ('Muddler Minnow', 'fly', 'streamer'),
  ('No Hackle BWO', 'fly', 'dry'),
  ('Oki Kebari', 'fly', 'wet'),
  ('One-Feather Kebari', 'fly', 'wet'),
  ('Orange Stimulator', 'fly', 'dry'),
  ('Pale Morning Dun', 'fly', 'dry'),
  ('Parachute Adams', 'fly', 'dry'),
  ('Parachute Ant', 'fly', 'dry'),
  ('Parachute Hopper', 'fly', 'dry'),
  ('Partridge and Green', 'fly', 'wet'),
  ('Partridge and Orange', 'fly', 'wet'),
  ('Partridge and Yellow', 'fly', 'wet'),
  ('Pat''s Rubber Legs', 'fly', 'nymph'),
  ('Perdigon', 'fly', 'nymph'),
  ('Pheasant Tail Nymph', 'fly', 'nymph'),
  ('Poison Tung', 'fly', 'nymph'),
  ('Prince Nymph', 'fly', 'nymph'),
  ('Psycho Prince', 'fly', 'nymph'),
  ('Quigley''s Film Critic', 'fly', 'emerger'),
  ('Rainbow Egg', 'fly', 'nymph'),
  ('Rainbow Warrior', 'fly', 'nymph'),
  ('Red Copper John', 'fly', 'nymph'),
  ('Red Quill', 'fly', 'dry'),
  ('Renegade', 'fly', 'dry'),
  ('Reverse Hackle Kebari', 'fly', 'wet'),
  ('Royal Coachman', 'fly', 'dry'),
  ('Royal Trude', 'fly', 'dry'),
  ('Royal Wulff', 'fly', 'dry'),
  ('RS2', 'fly', 'emerger'),
  ('Rubber Legs Hopper', 'fly', 'dry'),
  ('Sakasa Kebari', 'fly', 'wet'),
  ('Salmonfly', 'fly', 'dry'),
  ('San Juan Worm', 'fly', 'nymph'),
  ('Sculpzilla', 'fly', 'streamer'),
  ('Sexy Walt''s', 'fly', 'nymph'),
  ('Shuttlecock Emerger', 'fly', 'emerger'),
  ('Slate Drake', 'fly', 'dry'),
  ('Slumpbuster', 'fly', 'streamer'),
  ('Soft Hackle', 'fly', 'wet'),
  ('Soft Hackle Emerger', 'fly', 'emerger'),
  ('Sparkle Dun', 'fly', 'dry'),
  ('Sparkle Minnow', 'fly', 'streamer'),
  ('Sparkle Pupa', 'fly', 'emerger'),
  ('Spanish Bullet', 'fly', 'nymph'),
  ('Squirmy Worm', 'fly', 'nymph'),
  ('Stimulator', 'fly', 'dry'),
  ('Takayama Sakasa Kebari', 'fly', 'wet'),
  ('Thin Mint', 'fly', 'streamer'),
  ('Top Secret Midge', 'fly', 'nymph'),
  ('Trico', 'fly', 'dry'),
  ('Trude', 'fly', 'dry'),
  ('Twenty Incher', 'fly', 'nymph'),
  ('Turd', 'fly', 'nymph'),
  ('Tungsten Jig PT', 'fly', 'nymph'),
  ('Walt''s Worm', 'fly', 'nymph'),
  ('WD-40', 'fly', 'emerger'),
  ('White Wulff', 'fly', 'dry'),
  ('Woolly Bugger', 'fly', 'streamer'),
  ('Woolly Sculpin', 'fly', 'streamer'),
  ('Woolhead Sculpin', 'fly', 'streamer'),
  ('X-Caddis', 'fly', 'dry'),
  ('Yellow Sally', 'fly', 'dry'),
  ('Zoo Cougar', 'fly', 'streamer'),
  ('Zebra Midge', 'fly', 'nymph'),
  ('Zonker', 'fly', 'streamer'),
  ('Zug Bug', 'fly', 'nymph'),
  ('Trophy Dungeon', 'fly', 'streamer')
on conflict (name, type) do nothing;
